models/__init__.py
__author__ = 'greatghoul'

models/docs.py
from extensions import db

class Doc(db.Model):
    __tablename__ = 'local_docs'

    slug = db.Column(db.String, primary_key=True)
    name = db.Column(db.String, nullable=False)
    path = db.Column(db.String, nullable=False)

forms/__init__.py
#-*- coding:utf-8 -*-
from flask import url_for, redirect
from helpers import get_redirect_target, is_safe_url
from flask.ext.wtf import Form, HiddenField

class RedirectForm(Form):
    next = HiddenField()

    def __init__(self, *args, **kwargs):
        Form.__init__(self, *args, **kwargs)
        if not self.next.data:
            self.next.data = get_redirect_target() or ''

    def redirect(self, endpoint='index', **values):
        if is_safe_url(self.next.data):
            return redirect(self.next.data)
        target = get_redirect_target()
        return redirect(target or url_for(endpoint, **values))

forms/docs.py
#-*- coding: utf-8 -*-

from flask.ext import wtf
from forms import RedirectForm

class DocForm(RedirectForm):
    name = wtf.TextField('Name', validators=[ \
            wtf.Required('Missing document name') ])
    path = wtf.TextField('Path', validators=[ \
            wtf.Required('Missing document path') ])
    slug = wtf.TextField('Slug', validators=[ \
            wtf.Required('Missing document slug') ])

main.py
#-*- coding: utf-8 -*-
import sys, logging, filters
logger = logging.getLogger(__name__)

from flask import Flask, url_for, abort
from extensions import db

def make_application():
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_pyfile('config.py')
    logging.basicConfig(level=app.config['LOGGER_LEVEL'], \
                        format=app.config['LOGGER_FORMAT'])

    # Setup sqlalchemy
    db.init_app(app)

    @app.after_request
    def after_request(response):
        try:
            db.session.commit()
        except Exception:
            db.session.rollback()
            abort(500)
        return response

    # blueprints
    from views import docs
    app.register_blueprint(docs, url_prefix='/docs')

    # Config jinjia global variables
    app.jinja_env.filters['error_class'] = filters.error_class
    app.jinja_env.filters['error_text'] = filters.error_text
    app.jinja_env.filters['dateformat'] = filters.dateformat
    app.jinja_env.filters['empty'] = filters.empty
    app.jinja_env.globals['static'] = (
        lambda filename: url_for('static', filename=filename))

    return app

def runserver():
    app = make_application()
    app.run(app.config['HOST'], app.config['PORT'], app.config['DEBUG'])

def initdb():
    app = make_application()
    db.app = app
    db.drop_all()
    db.create_all()
    logger.info('Database reseted')

if __name__ == '__main__':
    if len(sys.argv) == 1:
        print 'Usage: python main.py <command>'
    else:
        command = sys.argv[1]
        command_action = globals().get(command)
        if callable(command_action):
            command_action()
        else:
            print 'Command "%s" is not avaiable' % command

views/__init__.py
#-*- coding: utf-8 -*-
from docs import docs

__all__ = [ 'docs' ]

views/docs.py
#-*- coding:utf-8 -*-
import logging
logger = logging.getLogger(__name__)

from flask import Blueprint, redirect, url_for, send_file, \
                  render_template, flash, request, current_app
from extensions import db
from models.docs import Doc
from forms.docs import DocForm
import os

HOME_PAGES = ['index.html', 'index.htm', 'default.html', 'default.htm']

docs = Blueprint('docs', __name__)

@docs.route('/', methods=['GET'])
def index():
    keyword = request.args.get('q', None)
    page = int(request.args.get('page', '1'))
    logger.info('Keyworkd %s', keyword)
    query = keyword and Doc.query.filter(Doc.name.like(u'%%%s%%' % keyword)) or Doc.query
    pagination = query.paginate(page, per_page=current_app.config.get('PAGE_SIZE', 20))
    # docs = pagination.items
    return render_template('docs/index.html', pagination=pagination)

@docs.route('/create', methods=['GET', 'POST'])
def create():
    form = DocForm(csrf_enabled=False)
    if form.validate_on_submit():
        doc = Doc()
        logger.info(form.populate_obj(doc))
        db.session.add(doc)
        flash('Document created successfully.', 'success')
        return redirect('.index')
    else:
        return render_template('docs/create.html', form=form)

@docs.route('/update/<slug>/', methods=['GET', 'POST'])
def update(slug):
    doc = Doc.query.filter_by(slug=slug).first()
    if doc is None:
        flash('Document <strong>%s</strong> is missing.', 'error')
        return redirect('.index')

    form = DocForm(csrf_enabled=False)
    if form.validate_on_submit():
        form.populate_obj(doc)
        flash('Document updated successfully.', 'success')
        return redirect('.index')
    else:
        not form.errors and form.process(obj=doc)
        return render_template('docs/create.html', form=form)

@docs.route('/destroy/<slug>/')
def destroy(slug):
    doc = Doc.query.filter_by(slug=slug).first()
    flash(u'Document <storng>%s</strong> deleted successfully.' % slug, 'success') 
    db.session.delete(doc)
    return redirect(url_for('.index'))

@docs.route('/doc/<slug>/')
@docs.route('/doc/<slug>/<path:filename>')
def view(slug, filename=''):
    doc = Doc.query.filter_by(slug=slug).first_or_404()
    if doc:
        doc_file = os.path.join(doc.path, filename)
        if os.path.isfile(doc_file):
            return send_file(doc_file)
        elif os.path.isdir(doc_file):
            if filename and not filename.endswith('/'):
                return redirect(url_for('.view', slug=slug, filename=filename+'/'))
            else:
                for page in HOME_PAGES:
                    if os.path.exists(os.path.join(doc_file, page)):
                        return redirect(url_for('.view', slug=slug, filename=filename + page))

templates/_helpers.html
{% macro script_tag(filename, scope=None) -%}
<script type="text/javascript" src="{{ url_for(scope and ('%s.static' % scope) or 'static', filename=filename) }}"></script>
{%- endmacro %}

{%- macro style_tag(filename, scope=None) -%}
<link rel="stylesheet" type="text/css" href="{{ url_for(scope and ('%s.static' % scope) or 'static', filename=filename) }}" />
{%- endmacro %}

templates/_pagination.html
{% macro render_pagination(pagination, endpoint, args) %}
<div class="pagination pagination-small">
    <ul>
        <li class="{{ pagination.has_prev and ' ' or 'disabled' }}">
            <a href="{{ pagination.has_prev and url_for(endpoint, page=pagination.prev_num, **args) or 'javascript:;' }}">«</a>
        </li>
        {%- for page in pagination.iter_pages() %}
        <li class="{{ (page == pagination.page) and 'active' or '' }} {{ page | empty('disabled') }}">
            {%- if page -%}
                {%- if page == pagination.page -%}
                <a href="javascript:;">{{ page }}</a>
                {%- else -%}
                <a href="{{ url_for(endpoint, page=page, **args) }}">{{ page }}</a>
                {%- endif -%}
            {%- else -%}
            <a href="javascript:;">...</a>
            {%- endif -%}
        </li>
        {%- endfor %}
        <li class="{{ pagination.has_next and ' ' or 'disabled' }}">
            <a href="{{ pagination.has_next and url_for(endpoint, page=pagination.next_num, **args) or 'javascript:;' }}">»</a>
        </li>
    </ul>
</div>
{% endmacro %}

templates/docs/_form.html
<form class="form-horizontal" method="POST" action="">
    {{ form.hidden_tag() }}
    <div class="control-group {{ form.name | error_class }}">
        <label class="control-label">{{ form.name.label }}</label>
        <div class="controls">
            {{ form.name(placeholder='Document Name', class='input-xlarge') }}
            <span class="help-block">{{ form.name | error_text }}</span>
        </div>
    </div>

    <div class="control-group {{ form.slug | error_class }}">
        <label class="control-label">{{ form.slug.label }}</label>
       <div class="controls">
           <div class="input-prepend">
               <span class="add-on">{{ request.url_root }}docs/doc/</span>
               {{ form.slug(placeholder='slug', class='input-medium') }}
           </div>
            <span class="help-block">{{ form.slug | error_text }}</span>
        </div>
    </div>

    <div class="control-group {{ form.path | error_class }}">
        <label class="control-label">{{ form.name.label }}</label>
        <div class="controls">
            {{ form.path(placeholder='Document root directory', class='input-xxlarge') }}
            <span class="help-block">{{ form.path | error_text }}</span>
        </div>
    </div>

    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="reset" class="btn">Reset</button>
        <a href="{{ url_for('docs.index') }}" class="btn-link">Back</button>
    </div>
</form>

templates/docs/create.html
{% extends 'layout.html' %}

{% block nav_active %}
    <span class="divider">/</span>
    <li class="active">Create new document</li>
{% endblock %}

{% block content %}
    <div class="content">
        <div class="page-header">
            <h1>Add Document</h1>
        </div>
        
        {% include 'docs/_form.html' %}
    </form>
{% endblock %}

templates/docs/index.html
{% extends 'layout.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="content">

    <div class="page-header">
        <a href="{{ url_for('docs.create') }}" class="btn btn-success pull-right">Add Document</a>
        
        <form class="form-search pull-right" style="margin-right: 20px;">
          <input type="text" name="q" class="input-large" placeholder="Type to search ...">
          <button type="submit" class="btn btn-primary">Search</button>
        </form>
        
        <h1>Docs Home</h1>
    </div>

    <table class="table table-bordered table-striped table-hover table-condensed">
        <tr>
            <th>Name</th>
            <th>Path</th>
            <th width="100">Actions</th>
        </tr>
        {% for doc in pagination.items %}
            <tr>
                <td><a href="{{ url_for('.view', slug=doc.slug) }}" target="_blank">{{ doc.name }}</a></td>
                <td><a href="javascript:window.open('file://{{ doc.path }}');" class="muted">{{ doc.path }}</a></td>
                <td>
                    <a href="{{ url_for('docs.update', slug=doc.slug) }}" class="btn btn-mini btn-primary">Edit</a>
                    <a href="{{ url_for('docs.destroy', slug=doc.slug) }}" data-confirm="Remove it or not?" class="btn btn-mini btn-danger">Remove</a>
                </td>
            </tr>
        {% endfor %}
    </table>

    {% import '_pagination.html' as p %}
    {{ p.render_pagination(pagination, 'docs.index', dict(q=request.args.get('q'))) }}
</div>
{% endblock %}

templates/docs/new.html
{% extends 'layout.html' %}

{% block nav_active %}
    <span class="divider">/</span>
    <li class="active">Create new document</li>
{% endblock %}

{% block content %}
    <div class="content">
        <div class="page-header">
            <h1>Add Document</h1>
        </div>
        
        {% include 'docs/_form.html' %}
    </form>
{% endblock %}

templates/docs/update.html
{% extends 'layout.html' %}

{% block nav_active %}
    <span class="divider">/</span>
    <li class="active">Update: <strong>{{ doc.name }}</strong></li>
{% endblock %}

{% block content %}
    <form class="form form-horizontal" method="POST" action="{{ url_for('docs.update', doc_id=doc.id) }}">
        <div class="control-group">
            <label class="control-label">Name</label>
            <div class="controls">
                <input type="text" name="name" placeholder="Document Name" class="input-xlarge" value="{{ doc.name }}" />
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Slug</label>
            <div class="controls">
                <span>{{ request.url_root }}docs/doc/</span>
                <input type="text" name="slug" class="input-medium" placeholder="slug" value="{{ doc.slug }}" />
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Root directory</label>
            <div class="controls">
                <input type="text" name="path" class="input-xxlarge" placeholder="Document root directory" value="{{ doc.path }}" />
            </div>
        </div>

        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Update</button>
            <button type="reset" class="btn">Reset</button>
        </div>
    </form>
{% endblock %}

templates/layout.html
<!DOCTYPE HTML>
{% import '_helpers.html' as tags %}
<html>
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset='utf-8" />
        <title>{% block title %}{% endblock %} - Doc Books</title>

        <!-- Global stylesheets -->
        <link rel="stylesheet" href="{{ static('lib/bootstrap/css/bootstrap.css') }}" />
        <link rel="stylesheet" href="{{ static('css/local.css') }}" />

        <!-- User stylesheets -->
        {% block styles %}{% endblock %}

        <!-- Global scripts -->
        <script type="text/javascript" src="{{ static('lib/jquery-1.7.2.min.js') }}"></script>
        <script type="text/javascript" src="{{ static('lib/bootstrap/js/bootstrap.min.js') }}"></script>
        <script type="text/javascript" src="{{ static('js/helpers.js') }}"></script>
        <script type="text/javascript" src="{{ static('js/local.js') }}"></script>


        <!-- User scripts -->
        {% block scripts %}{% endblock %}
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="/">Local</a>
                    <ul class="nav">
                        <li><a href="{{ url_for('docs.index') }}">Docs</a></li>
                    </ul>
                </div>
            </div>
        </div>
        
        <div class="container">
            
            <div class="alert-messages">
                {% for category, message in  get_flashed_messages(with_categories=true) %}
                    <div class="alert alert-{{ category | default('info') }}">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        {{ message | safe }}
                    </div>
                {% endfor %}
            </div>

            {% block content %}{% endblock %}
            <div class="footer">{% block footer %}{% endblock %}</div>
        </div>
    </body>
</html>